### ISSUE TITLE
repo is not open source

### ISSUE THREAD

**Issue by ghost** [psarna/edgemail#1]
this:

https://github.com/psarna/edgemail/blob/0b71edd22d62eb5ca4a1893086b14f70730a0a02/Cargo.toml#L5

is not enough to designate a work as MIT. you would need to include a full copy of the license. you may not care about that, but some people wont be able to use the code unless you do that.

**Comment by xet7** [comment]
I write and contribute to MIT and other http://copyfree.org licensed FOSS code.

**Comment by psarna** [comment]
Oh thanks, didn't realize. Just added the license text. @4cq2 feel free to close the issue if it works for you now!

**Comment by ghost** [comment]
thank you Mr deer head man
