### ISSUE TITLE
Should block privileged aliases (postmaster etc.)

### ISSUE THREAD

**Issue by hannob** [psarna/edgemail#2]
There's a security problem with this code. It would be possible for an adversary to register a TLS certificate for the service, as some certificate authorities use email validation to check the ownership of a domain.

To prevent this the aliases ‘admin’, ‘administrator’, ‘webmaster’, ‘hostmaster’, and ‘postmaster’ should be blocked in any service offering mail inboxes of any form. This is specified in the so-called Baseline Requirements, a standard for certificate authorities:
https://cabforum.org/baseline-requirements-documents/

**Comment by psarna** [comment]
Makes sense! Thanks, will fix

**Comment by psarna** [comment]
@hannob just curious -- do I understand correctly that the threat here is for an attacker to be able to register a TLS certificate, and then spoof `idont.date` domain and pretend that they are `idont.date`, effectively giving them man-in-the-middle capabilities for https? If so, given that all email addresses are already public as a feature, the threat is perhaps less severe than in other projects, e.g. ones that actually let you store private information. In any case, thanks for a very informative report, and I'll fix the issue soon, as per the baseline!

**Comment by hannob** [comment]
Yes, that's basically the scenario. Though note an attacker could not just read the content, but also manipulate it.
